apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "speclist-platform.fullname" . }}-web
  labels:
    {{- include "speclist-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "speclist-platform.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
              name: http
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
