apiVersion: v1
kind: Service
metadata:
  name: {{ include "speclist-platform.fullname" . }}-web
  labels:
    {{- include "speclist-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
